routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// Front Pages
Route::get('/', 'FrontPageController@index')->name('index');
Route::get('about', 'FrontPageController@about')->name('about');
Route::get('contact', 'FrontPageController@contact')->name('contact');
Route::get('terms', 'FrontPageController@terms')->name('terms');

Route::post('contact', 'FrontPageController@postContact')->name('contact.post');

// Cart
Route::post('addToCart', 'CartController@addToCart')->name('cart.addToCart');
Route::get('pluckItem/{position}', 'CartController@pluckItem')->name('cart.pluckItem');

// Testing route
Route::get('test', function() {
	return view('privacy');
});

// Products in Front Page
Route::get('products/{uri}', 'ProductController@showByUri')->name('products.showByUri');
Route::get('products/category/{category_name}', 'FrontPageController@showProductByCategory')->name('products.showByCategory');
Route::get('search/', 'FrontPageController@searchProduct')->name('products.searchNavbar');
Route::resource('products', 'ProductController');

// Members Area
Route::group([ 
	'middleware' => ['web', 'auth'],
], function() {
	// MemberController
	Route::get('/member/cart/{user_id?}', 'MemberController@myCart')->name('members.carts');
	Route::get('/member/profile/{user_id?}', 'MemberController@showMemberProfile')->name('profile');
	Route::get('/member/privacy/{user_id}', 'MemberController@editPassword')->name('members.privacy');
	Route::get('/member/invoices/{user_id?}', 'MemberController@memberInvoices')->name('members.invoices');
	Route::get('/member/invoices/view/{invoice_id}', 'MemberController@viewMemberInvoice')->name('members.viewInvoice');

	// UserController
	Route::get('/member/{user_id}/get_details', 'UserController@getUserData')->name('users.data');
	Route::match(['PUT', 'PATCH'], '/member/profile/{user_id}/update', 'UserController@updateMember')->name('profile.update');
	Route::match(['PUT', 'PATCH'], '/member/profile/{user_id}/profile_photo/update', 'UserController@updateProfilePicture')->name('profile.updateProfilePhoto');
	Route::match(['PUT', 'PATCH'], 'member/privacy/{user_id}/update', 'UserController@updatePassword')->name('members.updatePassword');

	// Cart Controller
	Route::post('/member/cart/{user_id}/checkout', 'CartController@checkout')->name('members.checkoutCart');
	Route::delete('/member/cart/{cart_id}/destroy', 'CartController@removeFromCart')->name('members.destroyCart');

	// Shipping Controller
	Route::get('/member/shipping_address/{address_id}/get_details', 'ShippingController@getShippingAddressData')->name('members.getShippingAddressData');
	Route::post('/member/{user_id?}/shipping_address/', 'ShippingController@addShippingAddress')->name('members.addShippingAddress');
	Route::match(['PUT', 'PATCH'], '/member/shipping_address/{address_id}', 'ShippingController@updateShippingAddress')->name('members.updateShippingAddress');
	Route::delete('/member/shipping_address/{address_id}/destroy', 'ShippingController@destroyShippingAddress')->name('members.destroyShippingAddress');

	// TransactionController [Midtrans]
	Route::get('/member/pay', 'TransactionController@createPayment')->name('members.pay');
	Route::get('/member/payment/{midtrans_id}/status', 'TransactionController@updateMidtransPaymentStatus')->name('members.updateMidtransPaymentStatus');
});

// Midtrans Notification Reciever
Route::post('/recieve_payment_from_midtrans', 'TransactionController@recieveNotification');
Route::post('/member/pay/finish', 'TransactionController@finishPayment')->name('members.finishPayment');

Route::get('home', 'HomeController@index');

// Dashboard Routes
Route::get('/staff', 'Auth\LoginController@dashboardLogin')->name('login.staff');
Route::get('/admin', 'Auth\LoginController@dashboardLogin')->name('login.admin');

Route::group([ 
	'middleware' => ['web', 'auth'],
	'prefix' => 'dashboard',
	'as' => 'dashboard.',
], function() {
	Route::get('/', 'DashboardController@index')->name('index');

	// Notifications
	Route::get('notifications/{user_id}/read-all', 'NotificationController@readAllMyNotification')->name('notifications.readAll');

	// Invoices
	Route::get('invoices', 'DashboardController@invoices')->name('invoices');
	Route::get('invoices/{invoice_id}/get_details', 'InvoiceController@getInvoiceData')->name('invoices.getInvoiceData');
	Route::post('invoices/{invoice_id}/update_shipping', 'InvoiceController@insertOrUpdateShippingData')->name('invoices.insertOrUpdateShippingData');
	Route::post('invoices/{invoice_id}/manually_add_invoice_item', 'InvoiceController@addInvoiceItem')->name('invoices.manuallyAddInvoiceItem');
	Route::post('invoices/manually_create_invoice', 'InvoiceController@createInvoice')->name('invoices.manuallyCreateInvoice');
	Route::delete('invoices/{invoice_id}/destroy', 'InvoiceController@destroyInvoice')->name('invoices.destroy');

	// Users and Profiles
	Route::get('user/{user_id}/profile', 'DashboardController@showProfile')->name('users.profile');
	Route::get('user/{user_id}/get_details', 'UserController@getUserData')->name('users.data');
	Route::get('staffs', 'DashboardController@staffs')->name('users.staffs');
	Route::get('members', 'DashboardController@members')->name('users.members');
	Route::post('staffs', 'UserController@storeStaff')->name('staffs.store');
	Route::match(['PUT', 'PATCH'], 'user/{user_id}/update', 'UserController@updateMember')->name('users.members.update');
	Route::match(['PUT', 'PATCH'], 'user/{user_id}/self_update', 'UserController@updateMyDetails')->name('users.self-update');
	Route::match(['PUT', 'PATCH'], 'staff/{user_id}/update', 'UserController@updateStaff')->name('users.staffs.update');
	Route::delete('user/{user_id}/destroy', 'UserController@destroyUser')->name('users.destroy');

	// Carts
	Route::get('carts', 'DashboardController@membersCarts')->name('carts');
	Route::delete('carts/{user_id}/destroy_user_cart', 'CartController@destroyUserCart')->name('carts.destroyUserCart');

	// Products
	Route::get('sales', 'DashboardController@sales')->name('sales');
	Route::get('stocks', 'DashboardController@stocks')->name('stocks');
	Route::get('products/subcategory/{subcategoryName?}', 'DashboardController@productLists')->name('products.lists');
	Route::get('products/{product_id}', 'DashboardController@viewProduct')->name('products.showDetail');
	Route::get('products/{product_id}/get_details', 'ProductController@getProductData')->name('products.get-data');
	Route::match(['PUT', 'PATCH'], 'products/{product_id}/update_description', 'ProductController@updateDescription')->name('products.updateDescription');
	Route::delete('products/{product_id}/deleteAndRedirect', 'ProductController@destroyAndRedict')->name('products.destroyAndRedict');

	// Products Attribute
	Route::get('products/attribute/{attribute_id}/get_details', 'ProductsAttributeController@getAttributeDetails')->name('products.getAttributeData');
	Route::post('products/add_attribute', 'ProductsAttributeController@store')->name('products.attribute.store');
	Route::match(['PUT', 'PATCH'], 'products/attribute/{attribute_id}/update_attribute', 'ProductsAttributeController@update')->name('products.updateAttribute');
	Route::delete('products/attribute/{attribute_id}/destroy', 'ProductsAttributeController@destroy')->name('products.attribute.destory');

	// Products Terms
	Route::get('products/term/{product_id}/get_details', 'ProductsTermController@getTerms')->name('products.getTerms');
	Route::post('products/{product_id}/editorupdatewarranty', 'ProductsTermController@updateOrCreate')->name('products.term.updateOrCreate');

	// Products Dimension
	Route::post('products/{product_id}/add_dimension', 'ProductsDimensionController@store')->name('products.dimension.store');
	Route::match(['PUT', 'PATCH'], 'products/dimension/{dimension_id}/update', 'ProductsDimensionController@update')->name('products.dimension.update');
	Route::delete('products/dimension/{dimension_id}/destroy', 'ProductsDimensionController@destroy')->name('products.dimension.destory');

	// Products Photo
	Route::post('products/{product_id}/upload_photos', 'ProductsPhotoController@add')->name('products.photo.add');
	Route::match(['PUT', 'PATCH'], 'products/photo/{photo_id}/update', 'ProductsPhotoController@updatePhoto')->name('products.photo.update');
	Route::delete('products/photo/{photo_id}/destroy', 'ProductsPhotoController@destroy')->name('products.photo.destory');

	// Products Banner
	Route::match(['PUT', 'PATCH'], 'products/banner/{product_id}/updateOrCreateBanner', 'ProductsBannerController@updateOrCreate')->name('products.banner.updateOrCreate');
	Route::delete('products/banner/{banner_id}/destroy', 'ProductsBannerController@destroy')->name('products.banner.destory');

	// Feedbacks
	Route::get('feedbacks', 'DashboardController@feedbacks')->name('feedbacks');
	Route::get('feedbacks/{feedback_id}/get_details', 'ContactController@show')->name('feedbacks.show');
	Route::delete('feedbacks/{feedback_id}', 'ContactController@destroy')->name('feedbacks.destroy');

	Route::resources([
		'products' => 'ProductController',
	]);
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use PragmaRX\Countries\Package\Countries;

use Auth;
use Carbon\Carbon;
use Session;
use View;

use App\Cart;
use App\Contact;
use App\Stock;
use App\Invoice;
use App\InvoiceItem;
use App\User;
use App\Category;
use App\SubCategory;
use App\Brand;
use App\Product;
use App\Notification;
use App\Visitor;

class DashboardController extends Controller
{
	public $subcategories;
    public $notification;

    public function __construct()
    {
    	$this->middleware('auth');
        $this->middleware('sales');
    	$this->middleware('staff')->except(['index', 'sales']);
        $this->middleware('admin')->only(['staffs']);

    	// Navbar and SideBar Items
        $categories = Category::all();
    	$subcategories = SubCategory::all();
        $stocks = Stock::all();

        // Widgets
        $stockAmount = count(Stock::all());
        $orderAmount = count(Invoice::where('status', 'paid')->get());
        $staffAmount = count(User::where('role', 'staff')->get());
        $userAmount = count(User::where('role', 'user')->get());

        View::share('categories', $categories);
    	View::share('subcategories', $subcategories);
        View::share('subcategory', 'all');

        View::share('stocks', $stocks);
        View::share('stockAmount', $stockAmount);
        View::share('orderAmount', $orderAmount);
        View::share('staffAmount', $staffAmount);
        View::share('userAmount', $userAmount);

        $countries = Countries::all();
        View::share('countries', $countries->toArray());

        View::share('visitors', Visitor::all());
    }

    public function index()
    {
        $now = Carbon::now();
        $startOfDay = $now->copy()->startOfDay();
        $endOfDay = $now->copy()->endOfDay();

    	// 10 latest sales
    	$todaySales = Invoice::orderBy('created_at')
    		->where('created_at', '>=', $startOfDay)
            ->where('created_at', '<=', $endOfDay)
            ->where('status', '!=', 'unpaid')
            ->where('status', '!=', 'expired')
    		->get();

        // unshipped but paid invoices
        $unshippedSales = Invoice::where('status', 'paid')
            ->where('status', 'paid')
            ->get();

    	// 10 latest registered members
    	$latestMembers = User::where('role', 'user')
    		->orderBy('created_at')
    		->take(10)
    		->get();

    	return view('dashboards.index', compact([
            'unshippedSales','todaySales', 'latestMembers', 
    	]));
    }

    public function productLists($subcategoryName = 'all')
    {
        if($subcategoryName == 'all') {
            $products = Product::orderBy('created_at', 'ASC');
            $subcategory = 'All';
        } else {
            $subcategory = SubCategory::orderBy('created_at', 'ASC')->where('name', $subcategoryName)
                ->get()
                ->first();

            // if requested subcategory not found, go to 404
            if(!$subcategory) abort(404);

            $products = Product::where('subcategory_id', $subcategory->id);
        }

        $products = $products->paginate(8);

        return view('dashboards.product-lists.index', compact(['products', 'subcategory']));
    }

    public function viewProduct($product_id)
    {
        $product = Product::findOrFail($product_id);

        return view('dashboards.product-lists.view', compact(['product']));
    }

    public function stocks()
    {
        $products = Product::all();

        return view('dashboards.inventories', compact(['products']));
    }

    /*
     * ATTENTION THIS IS LEFT UNDONE!
     *
     */
    public function sales($phase = 'all')
    {
        $now = Carbon::now();

        if($phase == 'weekly') {
            $startOfPhase = $now->copy()->startOfWeek;
            $endOfPhase = $now->copy()->endOfWeek;
        } else if($phase == 'monthly') {
            $startOfPhase = $now->copy()->startOfMonth;
            $endOfPhase = $now->copy()->endOfMonth;
        } else if($phase == 'yearly') {
            $startOfPhase = $now->copy()->startOfYear;
            $endOfPhase = $now->copy()->endOfYear;
        }

        $sales = Invoice::where('status', '!=', 'unpaid');
        if($phase != 'all') {
            $sales = $sales->where('created_at', '>=', $startOfPhase)
                ->where('created_at', '<=', $endOfPhase);
        }
        $sales = $sales->get();

        return view('dashboards.sales-history', compact(['sales']));
    }

    public function invoices()
    {
        $invoices = Invoice::orderBy('created_at', 'DESC')->get();

        return view('dashboards.invoice-histories', compact(['invoices']));
    }

    public function membersCarts()
    {
        $carts = Cart::all()->groupBy(function($cart, $key) {
            $user = $cart->user;
            $profile = $user->details;

            return $profile->first_name . ' ' . $profile->last_name;
        });

        if($carts) {
            $carts->each(function($cart, $key) {
                $cart->userId = $cart->first()->user_id;
                $cart->lastAddedItem = $cart->sortBy('updated_at')->first()->updated_at;
            });
        }

        return view('dashboards.members-carts', compact(['carts']));
    }

    public function showProfile($user_id)
    {
        $user = User::findOrFail($user_id);
        $userDetail = $user->details;

        return view('dashboards.users-management.view-profile', compact(['user', 'userDetail']));
    }

    public function staffs()
    {
        Session::put('selectedUser', null);
        $staffs = User::where('role', '!=', 'user');
        if(Auth::user()->role != 'admin') // if not admin, exclude show admin
            $staffs = $staffs->where('role', '!=', 'admin');
        $staffs = $staffs->get();

        return view('dashboards.users-management.staff-lists', compact(['staffs']));
    }

    public function members()
    {
        Session::put('selectedUser', null);
        $members = User::where('role', 'user')->get();

        return view('dashboards.users-management.member-lists', compact(['members']));
    }

    public function feedbacks()
    {
        $feedbacks = Contact::all();

        $userAmount = count(User::where('role', 'user')->get());
        $latestMembers = User::where('role', 'user')
            ->orderBy('created_at')
            ->take(10)
            ->get();

        return view('dashboards.feedbacks', compact(['userAmount', 'latestMembers', 'feedbacks']));
    }
}

resources/views/dashboards/product-lists/index.blade.php
@extends('layouts.dashboards-app.app')

@section('content')

<script type="text/javascript">
    function getProductData(productId) {
        $.ajax({
            type: 'GET',
            url: '/dashboard/products/' + productId + '/get_details',
            cache: false,
            dataType: 'JSON',
            success: function(data) {
                var product = JSON.parse($.parseJSON(JSON.stringify(data)));

                console.log(product)

                // $('#edit_product_photo').val()
                
                $('#edit_product_code').val(product.product_code)
                $('#edit_product_name').val(product.name)
                $('#edit_product_subcategory_id select').val(product.subcategory_id)
                $('#edit_product_buying_price').val(product.buying_price)
                $('#edit_product_price').val(product.price)
                $('#edit_product_amount').val(product.stock.amount)
                $('#edit_product_status').val(product.status)
                $('#edit_product_description').val(product.description)

                // change url value
                var url = '/dashboard/products/' + product.id
                $('#productUpdateForm').attr('action', url)
            }
        })
    }

    function confirmProductDelete(productId) {
        $.ajax({
            type: 'GET',
            url: '/dashboard/products/' + productId + '/get_details',
            cache: false,
            dataType: 'JSON',
            success: function(data) {
                var product = JSON.parse($.parseJSON(JSON.stringify(data)));

                var deleteUrl = '/dashboard/products/' + product.id

                console.log(deleteUrl)

                $('#delete_form').attr('action', deleteUrl)
                $('#csrf_delete').val('{{ csrf_token() }}');
            }
        })
    }
</script>

<div class="content-wrapper">
    <section class="content-header pt-3">
    	{{-- Title --}}
        <h1 class="text-black">
            {{ $subcategory === 'All' ? $subcategory : $subcategory->name }} Product List
        </h1>
    </section>

    <!-- Main content -->
    <section class="content">
        {{-- Card Box --}}
        @include('dashboards.widgets.card-box')
        
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                    	{{-- Title --}}
                        <h3 class="box-title text-black">
                            <i class="fa fa-lightbulb mr-2"></i>{{ $subcategory === 'All' ? $subcategory : $subcategory->name }} Product List
                        </h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div>
                    </div>

                    <div class="box-body">
                        @if ($errors->any())
                            <div class="alert alert-danger first">
                                @foreach ($errors->all() as $error)
                                {{ $error }} <br>
                                @endforeach
                            </div>

                            <br />
                        @endif
                        @if(session()->get('success'))
                            <div class="alert alert-success">
                                {{ session()->get('success') }}  
                            </div><br/>
                        @elseif(session()->get('error'))
                            <div class="alert alert-danger">
                                {{ session()->get('error') }}
                            </div><br/>
                        @endif
                        
                    	{{-- Button Add New --}}
                        <a class="btn btn-a mb-3" data-target="#modal-add-inventory" data-toggle="modal" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="Add">
                            <i class="fa fa-plus mr-2"></i>Add New Product
                        </a>

                        <div class="row mt-3">
                            @foreach($products as $key => $product)
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                                <div class="col-product mt-4">
                                    <img src="{{ asset($product->photo->directory) }}" class="img-product-lg mb-2" alt="User Image">
                                    <h4 class="text-black">{{ $product->name }} - {{ $product->product_code }}</h4>

                                    @if(Auth::user()->role == 'admin')
                                        <!-- Button Remove -->
                                        <a onclick="confirmProductDelete('{{ $product->id }}')" class="btn-action pull-right" data-target="#modal-delete" data-toggle="modal" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="Delete" style="cursor: pointer">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                        <!-- End Button Remove -->
                                    @endif

                                    <!-- Button Edit -->
                                    <a onclick="getProductData('{{ $product->id }}')" class="btn-action pull-right mr-1" data-target="#modal-edit-inventory" data-toggle="modal" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="Edit" style="cursor: pointer">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <!-- End Button Edit -->
									
									{{-- Status Stock --}}
                                    <span class="label label-success">{{ ucfirst($product->status) }}</span>

                                    {{-- Product Details --}}
                                    <div class="details">
                                        @foreach($product->attributes as $key => $attribute)
                                            <div class="details-info">
                                                <p>{{ $attribute->attribute_name }}</p>
                                                
                                                <span>
                                                    @foreach($attribute->values as $key => $value)
                                                        {{ $value->value }} 
                                                    @endforeach
                                                </span>
                                                
                                                <div class="clearfix"></div>
                                            </div>
                                        @endforeach
                                    
                                        <!-- Button View Details -->
                                        {{-- <a class="btn btn-a mt-2" data-target="#modal-view-product" data-toggle="modal" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="View">
                                            <i class="fa fa-plus mr-2"></i>View Details
                                        </a> --}}

                                        <a href="{{ route('dashboard.products.showDetail', $product->id) }}" class="btn btn-a mt-2" data-toggle="tooltip" data-placement="bottom" title="View">
                                            <i class="fa fa-plus mr-2"></i>View Details
                                        </a>
                                        <!-- Button View Details -->
                                    </div>
                                </div>
                            </div>
                            @endforeach

                            <!-- Pagination -->
                            <div class="col-xs-12 pl-0">
                                <div class="pagination">
                                    {{ $products->links('layouts.Pagination.pagination') }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@include('layouts.dashboards-app.modals.modal-inventories')

@endsection