routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// Front Pages
Route::get('/', 'FrontPageController@index')->name('index');
Route::get('about', 'FrontPageController@about')->name('about');
Route::get('contact', 'FrontPageController@contact')->name('contact');
Route::get('terms', 'FrontPageController@terms')->name('terms');

Route::post('contact', 'FrontPageController@postContact')->name('contact.post');

// Cart
Route::post('addToCart', 'CartController@addToCart')->name('cart.addToCart');
Route::get('pluckItem/{position}', 'CartController@pluckItem')->name('cart.pluckItem');

// Testing route
Route::get('test', function() {
	return view('privacy');
});

// Products in Front Page
Route::get('products/{uri}', 'ProductController@showByUri')->name('products.showByUri');
Route::get('products/category/{category_name}', 'FrontPageController@showProductByCategory')->name('products.showByCategory');
Route::get('search/', 'FrontPageController@searchProduct')->name('products.searchNavbar');
Route::resource('products', 'ProductController');

// Members Area
Route::group([ 
	'middleware' => ['web', 'auth'],
], function() {
	// MemberController
	Route::get('/member/cart/{user_id?}', 'MemberController@myCart')->name('members.carts');
	Route::get('/member/profile/{user_id?}', 'MemberController@showMemberProfile')->name('profile');
	Route::get('/member/privacy/{user_id}', 'MemberController@editPassword')->name('members.privacy');
	Route::get('/member/invoices/{user_id?}', 'MemberController@memberInvoices')->name('members.invoices');
	Route::get('/member/invoices/view/{invoice_id}', 'MemberController@viewMemberInvoice')->name('members.viewInvoice');

	// UserController
	Route::get('/member/{user_id}/get_details', 'UserController@getUserData')->name('users.data');
	Route::match(['PUT', 'PATCH'], '/member/profile/{user_id}/update', 'UserController@updateMember')->name('profile.update');
	Route::match(['PUT', 'PATCH'], '/member/profile/{user_id}/profile_photo/update', 'UserController@updateProfilePicture')->name('profile.updateProfilePhoto');
	Route::match(['PUT', 'PATCH'], 'member/privacy/{user_id}/update', 'UserController@updatePassword')->name('members.updatePassword');

	// Cart Controller
	Route::post('/member/cart/{user_id}/checkout', 'CartController@checkout')->name('members.checkoutCart');
	Route::delete('/member/cart/{cart_id}/destroy', 'CartController@removeFromCart')->name('members.destroyCart');

	// Shipping Controller
	Route::get('/member/shipping_address/{address_id}/get_details', 'ShippingController@getShippingAddressData')->name('members.getShippingAddressData');
	Route::post('/member/{user_id?}/shipping_address/', 'ShippingController@addShippingAddress')->name('members.addShippingAddress');
	Route::match(['PUT', 'PATCH'], '/member/shipping_address/{address_id}', 'ShippingController@updateShippingAddress')->name('members.updateShippingAddress');
	Route::delete('/member/shipping_address/{address_id}/destroy', 'ShippingController@destroyShippingAddress')->name('members.destroyShippingAddress');

	// TransactionController [Midtrans]
	Route::get('/member/pay', 'TransactionController@createPayment')->name('members.pay');
	Route::get('/member/payment/{midtrans_id}/status', 'TransactionController@updateMidtransPaymentStatus')->name('members.updateMidtransPaymentStatus');
});

// Midtrans Notification Reciever
Route::post('/recieve_payment_from_midtrans', 'TransactionController@recieveNotification');
Route::post('/member/pay/finish', 'TransactionController@finishPayment')->name('members.finishPayment');

Route::get('home', 'HomeController@index');

// Dashboard Routes
Route::get('/staff', 'Auth\LoginController@dashboardLogin')->name('login.staff');
Route::get('/admin', 'Auth\LoginController@dashboardLogin')->name('login.admin');

Route::group([ 
	'middleware' => ['web', 'auth'],
	'prefix' => 'dashboard',
	'as' => 'dashboard.',
], function() {
	Route::get('/', 'DashboardController@index')->name('index');

	// Notifications
	Route::get('notifications/{user_id}/read-all', 'NotificationController@readAllMyNotification')->name('notifications.readAll');

	// Invoices
	Route::get('invoices', 'DashboardController@invoices')->name('invoices');
	Route::get('invoices/{invoice_id}/get_details', 'InvoiceController@getInvoiceData')->name('invoices.getInvoiceData');
	Route::post('invoices/{invoice_id}/update_shipping', 'InvoiceController@insertOrUpdateShippingData')->name('invoices.insertOrUpdateShippingData');
	Route::post('invoices/{invoice_id}/manually_add_invoice_item', 'InvoiceController@addInvoiceItem')->name('invoices.manuallyAddInvoiceItem');
	Route::post('invoices/manually_create_invoice', 'InvoiceController@createInvoice')->name('invoices.manuallyCreateInvoice');
	Route::delete('invoices/{invoice_id}/destroy', 'InvoiceController@destroyInvoice')->name('invoices.destroy');

	// Users and Profiles
	Route::get('user/{user_id}/profile', 'DashboardController@showProfile')->name('users.profile');
	Route::get('user/{user_id}/get_details', 'UserController@getUserData')->name('users.data');
	Route::get('staffs', 'DashboardController@staffs')->name('users.staffs');
	Route::get('members', 'DashboardController@members')->name('users.members');
	Route::post('staffs', 'UserController@storeStaff')->name('staffs.store');
	Route::match(['PUT', 'PATCH'], 'user/{user_id}/update', 'UserController@updateMember')->name('users.members.update');
	Route::match(['PUT', 'PATCH'], 'user/{user_id}/self_update', 'UserController@updateMyDetails')->name('users.self-update');
	Route::match(['PUT', 'PATCH'], 'staff/{user_id}/update', 'UserController@updateStaff')->name('users.staffs.update');
	Route::delete('user/{user_id}/destroy', 'UserController@destroyUser')->name('users.destroy');

	// Carts
	Route::get('carts', 'DashboardController@membersCarts')->name('carts');
	Route::delete('carts/{user_id}/destroy_user_cart', 'CartController@destroyUserCart')->name('carts.destroyUserCart');

	// Products
	Route::get('sales', 'DashboardController@sales')->name('sales');
	Route::get('stocks', 'DashboardController@stocks')->name('stocks');
	Route::get('products/subcategory/{subcategoryName?}', 'DashboardController@productLists')->name('products.lists');
	Route::get('products/{product_id}', 'DashboardController@viewProduct')->name('products.showDetail');
	Route::get('products/{product_id}/get_details', 'ProductController@getProductData')->name('products.get-data');
	Route::match(['PUT', 'PATCH'], 'products/{product_id}/update_description', 'ProductController@updateDescription')->name('products.updateDescription');
	Route::delete('products/{product_id}/deleteAndRedirect', 'ProductController@destroyAndRedict')->name('products.destroyAndRedict');

	// Products Attribute
	Route::get('products/attribute/{attribute_id}/get_details', 'ProductsAttributeController@getAttributeDetails')->name('products.getAttributeData');
	Route::post('products/add_attribute', 'ProductsAttributeController@store')->name('products.attribute.store');
	Route::match(['PUT', 'PATCH'], 'products/attribute/{attribute_id}/update_attribute', 'ProductsAttributeController@update')->name('products.updateAttribute');
	Route::delete('products/attribute/{attribute_id}/destroy', 'ProductsAttributeController@destroy')->name('products.attribute.destory');

	// Products Terms
	Route::get('products/term/{product_id}/get_details', 'ProductsTermController@getTerms')->name('products.getTerms');
	Route::post('products/{product_id}/editorupdatewarranty', 'ProductsTermController@updateOrCreate')->name('products.term.updateOrCreate');

	// Products Dimension
	Route::post('products/{product_id}/add_dimension', 'ProductsDimensionController@store')->name('products.dimension.store');
	Route::match(['PUT', 'PATCH'], 'products/dimension/{dimension_id}/update', 'ProductsDimensionController@update')->name('products.dimension.update');
	Route::delete('products/dimension/{dimension_id}/destroy', 'ProductsDimensionController@destroy')->name('products.dimension.destory');

	// Products Photo
	Route::post('products/{product_id}/upload_photos', 'ProductsPhotoController@add')->name('products.photo.add');
	Route::match(['PUT', 'PATCH'], 'products/photo/{photo_id}/update', 'ProductsPhotoController@updatePhoto')->name('products.photo.update');
	Route::delete('products/photo/{photo_id}/destroy', 'ProductsPhotoController@destroy')->name('products.photo.destory');

	// Products Banner
	Route::match(['PUT', 'PATCH'], 'products/banner/{product_id}/updateOrCreateBanner', 'ProductsBannerController@updateOrCreate')->name('products.banner.updateOrCreate');
	Route::delete('products/banner/{banner_id}/destroy', 'ProductsBannerController@destroy')->name('products.banner.destory');

	// Feedbacks
	Route::get('feedbacks', 'DashboardController@feedbacks')->name('feedbacks');
	Route::get('feedbacks/{feedback_id}/get_details', 'ContactController@show')->name('feedbacks.show');
	Route::delete('feedbacks/{feedback_id}', 'ContactController@destroy')->name('feedbacks.destroy');

	Route::resources([
		'products' => 'ProductController',
	]);
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Webpatser\Uuid\Uuid;

use App\SubCategory;
use App\Stock;
use App\ProductPhoto;

class Product extends Model
{
    protected $table = 'products';
    protected $primaryKey = 'id';
    public $timestamps = true;
    public $incrementing = false;

    protected $fillable = [
        'product_code',

        'name',
        'uri',
        'price',
        'buying_price',

        'subcategory_id',

        'status',
        'description',

        'is_favourite',
    ];

    protected $hidden = [
        
    ];

    protected static function boot()
    {
    	parent::boot();

    	self::creating(function($model) {
            $model->id = Uuid::generate()->string;
            $model->uri = self::generateUri($model->name);

            // assigning category from sub category data
            $subcategory = SubCategory::findOrFail($model->subcategory_id);
            $model->category_id = $subcategory->category_id;
    	});

        self::updating(function($model) {
            if ($model->isDirty('name'))
                $model->uri = self::generateUri($model->name);
        });
    }

    public static function generateUri($productName)
    {
        return str_replace(' ', '-', strtolower($productName));
    }

    public static function createStock($id, $amount)
    {
        $stock = new Stock();

        $stock->product_id = $id;
        $stock->amount = $amount;

        return $stock->save();
    }

    public static function savePhoto($product_id, $file)
    {
        $photo = new ProductsPhoto();

        $photo->product_id = $product_id;
        $photo->directory = $photo->uploadPhoto($file);
        
        $photo->save();
    }

    public static function search($search = '')
    {
        $results = self::where('name', 'like', '%' . $search . '%')->get();

        return $results;
    }

    public static function searchPaginate($search = '')
    {
        $results = self::where('name', 'like', '%' . $search . '%')->paginate();

        return $results;
    }

    public function subcategory()
    {
        return $this->belongsTo('App\SubCategory', 'subcategory_id', 'id');
    }

    public function attributes()
    {
        return $this->hasMany('App\ProductsAttribute')->orderBy('attribute_name');
    }

    public function photo()
    {
        return $this->hasOne('App\ProductsPhoto', 'product_id', 'id');
    }

    public function photos()
    {
        return $this->hasMany('App\ProductsPhoto', 'product_id', 'id');
    }

    public function banner()
    {
        return $this->hasOne('App\ProductsBanner', 'product_id', 'id');
    }

    public function stock()
    {
        return $this->hasOne('App\Stock', 'product_id', 'id');
    }

    public function dimensions()
    {
        return $this->hasMany('App\ProductsDimension', 'product_id', 'id');
    }

    public function term()
    {
        return $this->hasOne('App\ProductsTerm', 'product_id', 'id');
    }
}

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')

<!-- BANNER TITLE -->
<div class="banner-top">
	<div class="container px-md-3 px-xl-6">
		<h2 class="title-a text-white">OUR PRODUCTS</h2>
	</div>
</div>
<!-- /BANNER TITLE -->


<!-- SECTION PRODUCTS -->
<div class="section-product">
	<div class="container px-md-3 px-xl-6">
		<!-- Breadcrumbs -->
		<ul class="breadcrumb">
		  	<li><a href="{{ route('index') }}">Home</a></li>
		  	<li><a href="{{ route('products.index') }}">Products</a></li>
		  	<li>{{ $subcategory ? $subcategory->name : 'All Products' }}</li>
		</ul>
		<!-- /Breadcrumbs -->

		<div class="row">
			<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-3 col-md-offset-0">
				<!-- Product Categories -->
				<div class="categories pb-5">
					<h3>Categories</h3>
					@foreach($categories as $key => $category)
						<details class="category">
							<summary class="category text-left">
								{{ $category->name }}
							</summary>
							<p>
								<ul>
									@foreach($category->subcategories as $key => $_subcategory)
										<li>
											<a href="/products/?subcategory={{ $_subcategory->name }}">{{ $_subcategory->name }}</a> <span>({{ count($_subcategory->products) ? count($_subcategory->products) : 0 }})</span>
										</li>
									@endforeach
								</ul>
							</p>
						</details>
					@endforeach
				</div>
	
				<!-- Price Option -->
				<div class="price pb-5">
					<h3>Price Range</h3>
					<div class="price-head">
						<form id="configForm" method="GET" action="">
							<div class="col-lg-12 price-head1">
								<h4 class="title-a text-black mt-0">Minimum</h4>
	                            <div class="price-top1">
	                                <span class="price-top">Rp</span>
	                                <input name="lowestPrice" type="text"  value="{{ isset($_GET['lowestPrice']) ? $_GET['lowestPrice'] : 0 }}">
	                            </div>
	                        </div>
							<div class="col-lg-12 price-head2">
								<h4 class="title-a text-black">Maximum</h4>
	                            <div class="price-top1">
	                                <span class="price-top">Rp</span>
	                                <input name="highestPrice" type="text"  value="{{ isset($_GET['highestPrice']) ? $_GET['highestPrice'] : 0 }}">
	                            </div>
	                        </div>
	                        <div class="col-lg-12 pl-0">
								<button type="submit" class="btn btn-d">Apply</button>
	                        </div>
						</form>
                	</div>
            	</div>
 			</div>

			
			<!-- Products Menu -->
			<div class="col-xs-12 col-md-9 px-6 px-md-3 pt-lg-4">
				<!-- Sort Option -->
				<div class="mens-toolbar">
					<p class="mr-3">Showing 1–6 of 12 results</p>
					<p>
			            <select form="configForm" name="perPage">
			                <option value="6" <?php if($perPage == 6) echo 'selected' ?>>6</option>
			                <option value="9" <?php if($perPage == 9) echo 'selected' ?>>9</option>
			                <option value="12" <?php if($perPage == 12) echo 'selected' ?>>12</option>
			            </select>
			        </p>
                	<p>
					<form class="mt-3">
						<input class="search" type="text" name="search" placeholder="Search.." id="search-item">
					</form>
					</p>	
		        </div>

		        @if ($errors->any())
                    <div class="alert alert-danger first">
                        @foreach ($errors->all() as $error)
                        {{ $error }} <br>
                        @endforeach
                    </div>

                    <br />
                @endif
                @if(session()->get('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}  
                    </div><br/>
                @elseif(session()->get('error'))
                    <div class="alert alert-danger">
                        {{ session()->get('error') }}
                    </div><br/>
                @endif

		        @foreach($products as $key => $product)
				<div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-0 simpleCart_shelfItem">
					<!-- Product 1 -->
					<div class="grid-pro">
						<div class="grid-product">
							<a href="{{ route('products.showByUri', $product->uri) }}">
								<div class="containerfade">
									<!-- Product Img -->
							     	<div class="imgHolder">
							      		<img src="{{ asset($product->photo->directory) }}" class="img-responsive" alt="">
							      	</div>
							    </div>
							</a>
						</div>
						<!-- Product Price -->
						<div class="featured-product-shop">
							<h6>
								<a href="{{ route('products.showByUri', $product->uri) }}">{{ $product->name }}</a>
							</h6>

							<p class="product-price">Rp. {{ number_format($product->price) }}</p>

							<form id="addToCart-{{ $product->id }}" action="{{ route('cart.addToCart') }}" method="POST">
								@csrf
								<input type="hidden" name="product_id" value="{{ $product->id }}">

								<!-- Quantity Box -->
								<div class="button-container mb-3">
									<button class="value-button cart-qty-minus" type="button" value="-">-</button>

		  								<input form="addToCart-{{ $product->id }}" type="number" id="number" name="amount" class="qty" maxlength="12" class="input-text qty" value="1" />

		  							<button class="value-button cart-qty-plus" type="button" value="+">+</button>
	  							</div>
							</form>

  							<!-- Button Cart -->
  							<div class="cart-button mt-2">
								<a class="btn-a item_add" onclick="$('#addToCart-{{ $product->id }}').submit()">Add To Cart</a>
							</div>
						</div>
					</div>
				</div>
				@endforeach
				
				<!-- Pagination -->
				<div class="col-xs-12 mt-4">
					<div class="pagination">
					  	{{ $products->links('layouts/Pagination/pagination') }}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>			
<!-- /SECTION PRODUCTS -->

@endsection